name: Tag Version Match

description: >
  Check if tag message corresponds
  to the version of package.json, Cargo.toml and so on.

inputs:
  file:
    description: >
      file path that contains version information
      e.g. ./package.json, ./Cargo.toml
    required: true
  query:
    description: >
      argument of yq command to extract the version of file such as package.json
      e.g. .version
  tag:
    description: usually, you do not have to use this input
    default: ${{ github.ref_name }}
    required: true


outputs:
# file-extension:
#   description: the extension of the input file
#   value: ${{ steps.file-extension.outputs.extension }}
  file-version:
    description: the version extracted using input file and query
    value: ${{ steps.file-version.outputs.version }}

runs:
  using: "composite"
  steps:
#   - id: file-extension
#     shell: bash
#     run: |
#       file=${{ inputs.file }}
#       extension=${file##*.}
#       echo extension=${extension} >> $GITHUB_OUTPUT

    - id: file-version
      shell: bash
      run: |
        version=$(yq -r -oy '${{ inputs.query }}' ${{ inputs.file }})
        echo version=${version} >> $GITHUB_OUTPUT
