name: Tag Version Match

description: >
  Check if tag message corresponds
  to the version of package.json, Cargo.toml and so on.

inputs:
  file:
    description: >
      file path that contains version information
      e.g. ./package.json, ./Cargo.toml
    required: true
  query:
    description: >
      argument of yq command to extract the version of file such as package.json
      e.g. .version
    required: true
  pattern:
    description: >
      extended regex of sed command to extract the version from tag
      (by default, first group is extracted)
    required: true
    default: '^v([0-9]+\.[0-9]+\.[0-9]+)$'
  nth-group:
    description: >
      the number of group to extract from pattern
    required: true
    default: '1'

outputs:
  file-version:
    description: the version extracted using input file and query
    value: ${{ steps.file-version.outputs.version }}
  tag-version:
    description: the version extracted from tag
    value: ${{ steps.tag-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - id: file-version
      shell: bash
      run: |
        version=$(yq -r -oy '${{ inputs.query }}' ${{ inputs.file }})
        echo version=${version} >> $GITHUB_OUTPUT

    - id: tag-version
      shell: bash
      run: |
        # 625217715 is the id of this repository
        if [[
          -v TAG_VERSION_MATCH_TEST_INPUT &&
          ${{ github.repository_id }} != '625217715'
        ]]; then
          echo 'TAG_VERSION_MATCH_TEST_INPUT is reserved!'
          exit 1
        fi

        tag=${TAG_VERSION_MATCH_TEST_INPUT:-${{ github.ref_name }}}
        version=$(sed -En 's/${{ inputs.pattern }}/\${{ inputs.nth-group }}/p' <<< $tag)
        echo version=${version} >> $GITHUB_OUTPUT

    - id: compare-version
      if: ${{ github.ref_type == 'tag' }}
      shell: bash
      run: |
        [[ ${{ steps.file-version.outputs.version }} == ${{ steps.tag-version.outputs.version }} ]]
