name: Tag Version Match

description: >
  Check if tag message corresponds
  to the version of package.json, Cargo.toml and so on.

inputs:
  file:
    description: >
      file path that contains version information
      e.g. ./package.json, ./Cargo.toml
    required: true
  query:
    description: >
      argument of yq command to extract the version of file such as package.json
      e.g. .version

outputs:
  file-version:
    description: the version extracted using input file and query
    value: ${{ steps.file-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - id: file-version
      shell: bash
      run: |
        version=$(yq -r -oy '${{ inputs.query }}' ${{ inputs.file }})
        echo version=${version} >> $GITHUB_OUTPUT

    # TODO
    - id: tag-version
      shell: bash
      run: |
        # 625217715 is the id of this repository
        if [[
          -v TAG_VERSION_MATCH_TEST_INPUT &&
          ${{ github.repository_id }} != '625217715'
        ]]; then
          echo 'TAG_VERSION_MATCH_TEST_INPUT is reserved!'
          exit 1
        fi

        tag=${TAG_VERSION_MATCH_TEST_INPUT:-${{ github.ref_name }}}
        echo $tag

    - id: compare-version
      if: ${{ github.ref_type == 'tag' }}
      shell: bash
      run: |
        # TODO
        [[ ${{ steps.file-version.outputs.version }} == ${{ steps.tag-version.outputs.version }} ]]
