on: [push]
jobs:
  json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cat <<EOS > package.json
          {
            "version": "1.0.0"
          }
          EOS
      - uses: .

