on: [push]
jobs:
  json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cat <<EOS > package.json
          {
            "version": "1.0.0"
          }
          EOS
      - id: test
        uses: ./
        with:
          file: ./package.json
          query: .version
      - run: |
          echo ${{ steps.test.outputs.file-extension }}
          echo ${{ steps.test.outputs.file-version }}
