on: [push]
jobs:
  file-query:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-case:
          - file: package.json
            text: |
              {
                "version": "1.0.0"
              }
            query: .version
          - file: Cargo.toml
            text: |
              [package]
              version = "1.0.0"
            query: .package.version
    steps:
      - uses: actions/checkout@v3
      - run: |
          cat <<EOF > ${{ matrix.test-case.file }}
          ${{ matrix.test-case.text }}
          EOF
      - id: test
        uses: ./
        with:
          file: ${{ matrix.test-case.file }}
          query: ${{ matrix.test-case.query }}
      - run: |
          [[ ${{ steps.test.outputs.file-version }} == "1.0.0" ]]

  tag-pattern-group:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-case:
          - tag: v1.0.0
            pattern: '^v([0-9]\.[0-9]\.[0-9])$'
            nth-group: '1'
          - tag: v1.0.0-beta
            pattern: '^v([0-9]\.[0-9]\.[0-9])(-beta)?$'
            nth-group: '1'
          - tag: 1.0.0
            pattern: '[0-9]\.[0-9]\.[0-9]'
            nth-group: '0'
    steps:
      - uses: actions/checkout@v3
      - run: |
          cat <<EOF > package.json
          {
            "version": "1.0.0"
          }
          EOF
      - id: test
        uses: ./
        env:
          TAG_VERSION_MATCH_TEST_INPUT: ${{ matrix.test-case.tag }}
        with:
          file: ./package.json
          query: .version
          pattern: '${{ matrix.test-case.pattern }}'
          nth-group: '${{ matrix.test-case.nth-group }}'
      - run: |
          [[ ${{ steps.test.outputs.file-version }} == ${{ steps.test.outputs.tag-version }} ]]
