on: [push]
jobs:
  json:
    runs-on: ubuntu-latest
    env:
      TAG_VERSION_MATCH_TEST_INPUT: v1.0.0
    steps:
      - uses: actions/checkout@v3
      - run: |
          cat <<EOF > package.json
          {
            "version": "1.0.0"
          }
          EOF
      - id: test
        uses: ./
        with:
          file: ./package.json
          query: .version
      - run: |
          echo ${{ steps.test.outputs.file-version }}

  toml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cat <<EOF > Cargo.toml
          [package]
          version = "1.0.0"
          EOF
      - id: test
        uses: ./
        with:
          file: ./Cargo.toml
          query: .package.version
      - run: |
          echo ${{ steps.test.outputs.file-version }}
